// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNfLEkXbazD08UOQLhL6s2XBO2Qr5HwVo',
    appId: '1:610685915691:web:d93ec0bdc069a0834dd06e',
    messagingSenderId: '610685915691',
    projectId: 'paramov-b4f20',
    authDomain: 'paramov-b4f20.firebaseapp.com',
    storageBucket: 'paramov-b4f20.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMkBO4AaA_rrtyX4YKoF8zoLhV0iCc_LU',
    appId: '1:610685915691:android:93f1a1ebac2a45d54dd06e',
    messagingSenderId: '610685915691',
    projectId: 'paramov-b4f20',
    storageBucket: 'paramov-b4f20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDimdMczdSX48DecZeXzp_2gfXLZKs0jmE',
    appId: '1:610685915691:ios:35d9926a4c0d59c94dd06e',
    messagingSenderId: '610685915691',
    projectId: 'paramov-b4f20',
    storageBucket: 'paramov-b4f20.appspot.com',
    iosBundleId: 'com.example.paramov',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDimdMczdSX48DecZeXzp_2gfXLZKs0jmE',
    appId: '1:610685915691:ios:abdfc896f566c74a4dd06e',
    messagingSenderId: '610685915691',
    projectId: 'paramov-b4f20',
    storageBucket: 'paramov-b4f20.appspot.com',
    iosBundleId: 'com.example.paramov.RunnerTests',
  );
}
